<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Exam extends \Application\Entity\Exam implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'imageurl', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'pointsIfCompleted', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'reducePercentageOuttime', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'insertDate', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'mandatory', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'totalitems', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'progOnCourse', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'course');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'imageurl', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'pointsIfCompleted', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'reducePercentageOuttime', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'insertDate', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'mandatory', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'totalitems', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'progOnCourse', '' . "\0" . 'Application\\Entity\\Exam' . "\0" . 'course');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Exam $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageurl($imageurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageurl', array($imageurl));

        return parent::setImageurl($imageurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageurl', array());

        return parent::getImageurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsIfCompleted($pointsIfCompleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsIfCompleted', array($pointsIfCompleted));

        return parent::setPointsIfCompleted($pointsIfCompleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsIfCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsIfCompleted', array());

        return parent::getPointsIfCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setReducePercentageOuttime($reducePercentageOuttime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReducePercentageOuttime', array($reducePercentageOuttime));

        return parent::setReducePercentageOuttime($reducePercentageOuttime);
    }

    /**
     * {@inheritDoc}
     */
    public function getReducePercentageOuttime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReducePercentageOuttime', array());

        return parent::getReducePercentageOuttime();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsertDate($insertDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsertDate', array($insertDate));

        return parent::setInsertDate($insertDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsertDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsertDate', array());

        return parent::getInsertDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMandatory($mandatory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMandatory', array($mandatory));

        return parent::setMandatory($mandatory);
    }

    /**
     * {@inheritDoc}
     */
    public function getMandatory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMandatory', array());

        return parent::getMandatory();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalitems($totalitems)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalitems', array($totalitems));

        return parent::setTotalitems($totalitems);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalitems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalitems', array());

        return parent::getTotalitems();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgOnCourse($progOnCourse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgOnCourse', array($progOnCourse));

        return parent::setProgOnCourse($progOnCourse);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgOnCourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgOnCourse', array());

        return parent::getProgOnCourse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCourse(\Application\Entity\Course $course = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourse', array($course));

        return parent::setCourse($course);
    }

    /**
     * {@inheritDoc}
     */
    public function getCourse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourse', array());

        return parent::getCourse();
    }

}
