<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Course extends \Application\Entity\Course implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'periodicityweek', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'durationweek', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'insertDate', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'emailtemplateurl', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'totalexams', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'activationstatus', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'weekday');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'description', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'periodicityweek', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'durationweek', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'insertDate', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'emailtemplateurl', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'totalexams', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'activationstatus', '' . "\0" . 'Application\\Entity\\Course' . "\0" . 'weekday');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Course $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodicityweek($periodicityweek)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodicityweek', array($periodicityweek));

        return parent::setPeriodicityweek($periodicityweek);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodicityweek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodicityweek', array());

        return parent::getPeriodicityweek();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationweek($durationweek)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationweek', array($durationweek));

        return parent::setDurationweek($durationweek);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationweek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationweek', array());

        return parent::getDurationweek();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsertDate($insertDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsertDate', array($insertDate));

        return parent::setInsertDate($insertDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsertDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsertDate', array());

        return parent::getInsertDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailtemplateurl($emailtemplateurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailtemplateurl', array($emailtemplateurl));

        return parent::setEmailtemplateurl($emailtemplateurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailtemplateurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailtemplateurl', array());

        return parent::getEmailtemplateurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalexams($totalexams)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalexams', array($totalexams));

        return parent::setTotalexams($totalexams);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalexams()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalexams', array());

        return parent::getTotalexams();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivationstatus(\Application\Entity\Activationstatus $activationstatus = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivationstatus', array($activationstatus));

        return parent::setActivationstatus($activationstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivationstatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivationstatus', array());

        return parent::getActivationstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeekday(\Application\Entity\Weekday $weekday = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeekday', array($weekday));

        return parent::setWeekday($weekday);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeekday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeekday', array());

        return parent::getWeekday();
    }

}
