<?php

namespace Platform\Entity\Repository;

/**
 * AccountHasBrandHasWidgetRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountHasBrandHasWidgetRepo extends \Doctrine\ORM\EntityRepository
{
}
