<?php

namespace Platform\Entity\Repository;

/**
 * AccountHasBrandHasPageHasWidgetRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountHasBrandHasPageHasWidgetRepo extends \Doctrine\ORM\EntityRepository
{
}
