<?php

namespace Platform\Entity\Repository;

/**
 * AccountmenustatusRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountmenustatusRepo extends \Doctrine\ORM\EntityRepository
{
}
