<?php

namespace Platform\Entity\Repository;

/**
 * AccountHasWidgetoptionRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountHasWidgetoptionRepo extends \Doctrine\ORM\EntityRepository
{
}
