<?php

namespace Platform\Entity\Repository;

/**
 * AccountHasMenuitemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountHasMenuitemRepo extends \Doctrine\ORM\EntityRepository
{
}
