<?php

namespace Platform\Entity\Repository;

/**
 * AccountstatusRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountstatusRepo extends \Doctrine\ORM\EntityRepository
{
}
