<?php

namespace Platform\Entity\Repository;

/**
 * AccountExtendsBrandHasWidgetUseServiceRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountExtendsBrandHasWidgetUseServiceRepo extends \Doctrine\ORM\EntityRepository
{
}
