<?php

namespace Platform\Entity\Repository;

/**
 * AccountHasPageRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountHasPageRepo extends \Doctrine\ORM\EntityRepository
{
}
