<?php

namespace Platform\Entity\Repository;

/**
 * AreaRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaRepo extends \Doctrine\ORM\EntityRepository
{
}
