<?php

namespace Platform\Entity\Repository;

/**
 * BrandRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepo extends \Doctrine\ORM\EntityRepository
{
}
