<?php

namespace Platform\Entity\Repository;

/**
 * BrandHasPageHasWidgetRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandHasPageHasWidgetRepo extends \Doctrine\ORM\EntityRepository
{
}
