<?php

namespace Platform\Entity\Repository;

/**
 * BrandHasWidgetRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandHasWidgetRepo extends \Doctrine\ORM\EntityRepository
{
}
