<?php

namespace Platform\Entity\Repository;

/**
 * BrandHasWidgetUseServiceRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandHasWidgetUseServiceRepo extends \Doctrine\ORM\EntityRepository
{
}
