<?php

namespace Platform\Entity\Repository;

/**
 * MenuitemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuitemRepo extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Gets all the available menu items
	 */
	public function findAllMenu()
	{
		$result = $this->createQueryBuilder('m')
		->select('m')
		->getQuery()
		->getArrayResult();
		return $result;
	}
}
