<?php

namespace Platform\Entity\Repository;

/**
 * MenuHasPageRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuHasPageRepo extends \Doctrine\ORM\EntityRepository
{
}
