<?php

namespace Platform\Entity\Repository;

/**
 * MenutypeRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenutypeRepo extends \Doctrine\ORM\EntityRepository
{
}
