<?php

namespace Platform\Entity\Repository;

/**
 * MenustatusRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenustatusRepo extends \Doctrine\ORM\EntityRepository
{
}
