<?php

namespace Platform\Entity\Repository;

use Platform\Entity\Page;

/**
 * PageHasWidgetRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 */
class PageHasWidgetRepo extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * Load all the widgets for the given page:
	 * the results are ordered by "position" field ascending
	 * @param Page $page
	 * @return array
	 */
	public function findByPage(Page $page)
	{
		$result = $this->createQueryBuilder('pw')
		->select('pw')
		->where('pw.page = :page')
		->setParameter('page', $page)
		->orderBy('pw.position','ASC')
		->getQuery()
		->getResult();
		
		return $result;
	}
}