<?php

namespace Platform\Entity\Repository;

/**
 * PageRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepo extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * Find all available pages
	 * @return array
	 */
	public function findAllPages()
	{
		$result = $this->createQueryBuilder('p')
		->select('p')
		->getQuery()
		->getResult();
		
		return $result;
	}
	
	/**
	 * Find a page by its code
	 * @param string $code Page code
	 */
	public function findByCode($code)
	{
		$result = $this->createQueryBuilder('p')
		->select('p')
		->where('p.code = :code')
		->setParameter('code', $code)
		->getQuery()
		->getResult();
		
		return $result;
	}
}