<?php

namespace Platform\Entity\Repository;

/**
 * ServiceRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepo extends \Doctrine\ORM\EntityRepository
{
}
