<?php

namespace Platform\Entity\Repository;

/**
 * WidgetRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepo extends \Doctrine\ORM\EntityRepository
{

	/**
	 * Find all available widgets
	 * @return array
	 */
	public function findAllWidgets()
	{
		$result = $this->createQueryBuilder('w')
		->select('w')
		->getQuery()
		->getResult();
	
		return $result;
	}
	
	/**
	 * Find a widget by its code
	 * @param string $code Widget code
	 */
	public function findByCode($code)
	{
		$result = $this->createQueryBuilder('w')
		->select('w')
		->where('w.code = :code')
		->setParameter('code', $code)
		->getQuery()
		->getResult();
	
		return $result;
	}
}
