<?php

namespace Platform\Entity\Repository;

/**
 * WidgetUseServiceRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetUseServiceRepo extends \Doctrine\ORM\EntityRepository
{
}
