<?php

namespace Platform\Entity\Repository;

/**
 * WidgettypeRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgettypeRepo extends \Doctrine\ORM\EntityRepository
{
}
