<?php

namespace Application\Entity\Repository;

/**
 * AccountRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepo extends \Doctrine\ORM\EntityRepository
{
}
