<?php

namespace Application\Entity\Repository;

/**
 * ActivationstatusRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationstatusRepo extends \Doctrine\ORM\EntityRepository
{
}
