<?php

namespace Application\Entity\Repository;

/**
 * AnswerRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepo extends \Doctrine\ORM\EntityRepository
{
}
