<?php

namespace Application\Entity\Repository;

/**
 * ClientHasCourseRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientHasCourseRepo extends \Doctrine\ORM\EntityRepository
{
}
