<?php

namespace Application\Entity\Repository;

use Application\Entity\Course;
use Application\Entity\Client;
use Doctrine\Common\Collections\Criteria;
/**
 * ClientHasCourseRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientHasCourseRepo extends \Doctrine\ORM\EntityRepository
{
	public function findByCourseAndClient(Course $course, Client $client)
	{
		
		$criteria = Criteria::create()->where(Criteria::expr()->eq('course',$course))->andWhere(Criteria::expr()->eq('client',$client));
		$result = $this->matching($criteria);
		if ($result->count()) return $result->getValues()[0];
		return null;
	}

	public function findByCourse(Course $course)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('course',$course));
		$result = $this->matching($criteria);
		return $result->getValues();
	}	

/*
	public function findByCourse(Course $course)
	{
		$q = $this->createQueryBuilder('cc')->select('cc')->where('course = :course')->getQuery();
		$q->setParameter('course', $course);
		return $q->getResult();
	}

*/
}
