<?php

namespace Application\Entity\Repository;

/**
 * ClientRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepo extends \Doctrine\ORM\EntityRepository
{
}
