<?php

namespace Application\Entity\Repository;

/**
 * ClientconfigurationRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientconfigurationRepo extends \Doctrine\ORM\EntityRepository
{
}
