<?php

namespace Application\Entity\Repository;

/**
 * ClientHasStudentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientHasStudentRepo extends \Doctrine\ORM\EntityRepository
{
}
