<?php

namespace Application\Entity\Repository;

/**
 * CourseRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepo extends \Doctrine\ORM\EntityRepository
{
}
