<?php

namespace Application\Entity\Repository;

use Application\Entity\Exam;
use Doctrine\Common\Collections\Criteria;
use Application\Entity\ExamHasItem;
/**
 * ExamHasItemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamHasItemRepo extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Acquisizione di tutti gli item per un esame
	 *
	 * @param Exam $exam
	 * @return array
	 */
	public function findByExam(Exam $exam)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('exam',$exam));
		$result = $this->matching($criteria);
		if ($result->count()) return $result->getValues();
		return array();
	}
	
	/**
	 * Acquisizione di un item per un esame, con esame e progressivo
	 * 
	 * @param Exam $exam
	 * @param int $progressive
	 * 
	 * @return ExamHasItem
	 */
	public function findByExamAndProgressive(Exam $exam, $progressive)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('exam',$exam))->andWhere(Criteria::expr()->eq('progressive',$progressive));
		$result = $this->matching($criteria);
		if ($result->count()) return $result->getValues()[0];
		return null;
	}
	
	
}
