<?php

namespace Application\Entity\Repository;

/**
 * ExamRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepo extends \Doctrine\ORM\EntityRepository
{
}
