<?php

namespace Application\Entity\Repository;

/**
 * ExamHasItemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamHasItemRepo extends \Doctrine\ORM\EntityRepository
{
}
