<?php

namespace Application\Entity\Repository;

/**
 * ImageRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepo extends \Doctrine\ORM\EntityRepository
{
}
