<?php

namespace Application\Entity\Repository;

/**
 * ItemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepo extends \Doctrine\ORM\EntityRepository
{
}
