<?php

namespace Application\Entity\Repository;

use Application\Entity\Item;
use Doctrine\Common\Collections\Criteria;
/**
 * ItemoptionRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemoptionRepo extends \Doctrine\ORM\EntityRepository
{
	
}
