<?php

namespace Application\Entity\Repository;

/**
 * ItemoptionRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemoptionRepo extends \Doctrine\ORM\EntityRepository
{
}
