<?php

namespace Application\Entity\Repository;

/**
 * ItemHasAnswerRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemHasAnswerRepo extends \Doctrine\ORM\EntityRepository
{
}
