<?php

namespace Application\Entity\Repository;

/**
 * ItemtypeRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemtypeRepo extends \Doctrine\ORM\EntityRepository
{
}
