<?php

namespace Application\Entity\Repository;

use Application\Entity\Item;
use Doctrine\Common\Collections\Criteria;
/**
 * ItemoptionRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemoptionRepo extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Acquisizione di tutti gli itemoptions per un item
	 *
	 * @param Item $item Item di riferimento
	 * @return array
	 */
	public function findByItem(Item $item)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('item', $item))->orderBy(array('id'=>'ASC'));
		$result = $this->matching($criteria);
		if ($result->count()) return $result;
		return null;
	}
}
