<?php

namespace Application\Entity\Repository;

/**
 * OptionRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionRepo extends \Doctrine\ORM\EntityRepository
{
}
