<?php

namespace Application\Entity\Repository;

/**
 * PrizeRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrizeRepo extends \Doctrine\ORM\EntityRepository
{}
