<?php

namespace Application\Entity\Repository;

/**
 * StudentgroupHasStudentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentgroupHasStudentRepo extends \Doctrine\ORM\EntityRepository
{
}
