<?php

namespace Application\Entity\Repository;

use Application\Entity\Student;
/**
 * StudentHasCourseRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasCourseRepo extends \Doctrine\ORM\EntityRepository
{
	
}
