<?php

namespace Application\Entity\Repository;

use Application\Entity\StudentHasCourseHasExam;
use Doctrine\Common\Collections\Criteria;
/**
 * StudentHasAnsweredToItemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasAnsweredToItemRepo extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * Acquisizione unico studente per identificativo
	 *
	 * @param string $identifier Identificativo utente della richiesta
	 * @return Student
	 */
	public function findByIdentifier($identifier)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('identifier', $identifier));
		$result = $this->matching($criteria);
		if ($result->count()) return($result->last());
		return null;
	}
	
	public function findByStudentCourseExam(StudentHasCourseHasExam $examForStudent)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('s'))
	} 
}
