<?php

namespace Application\Entity\Repository;

/**
 * StudentHasCourseRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasClientHasCourseRepo extends \Doctrine\ORM\EntityRepository
{
	
}
