<?php

namespace Application\Entity\Repository;

use Application\Entity\StudentHasCourseHasExam;
use Doctrine\Common\Collections\Criteria;

/**
 * StudentHasCourseHasExamRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasCourseHasExamRepo extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Acquisizione unico record sessione per identificativo
	 *
	 * @param string $identifier Identificativo sessione
	 * @return StudentHasCourseHasExam
	 */
	public function findByIdentifier($identifier)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('token', $identifier))->orderBy(array('id'=>'ASC'));
		$result = $this->findBy($criteria);
		if (is_array($result) && !empty($result)) return $result[0];
		return null;
	}
	
	/**
	 * Acquisizione di tutte le sessioni di esame per il corso indicato
	 * 
	 * @param StudentHasCourse $studentCourse
	 * @return array
	 */
	public function findByStudentOnCourse(StudentHasCourse $studentCourse)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('studentHasCourse',$studentCourse));
		return $this->findBy($criteria);
	}
}
