<?php

namespace Application\Entity\Repository;

use Application\Entity\Student;
use Doctrine\Common\Collections\Criteria;
/**
 * StudentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepo extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Acquisizione unico studente per identificativo
	 * 
	 * @param string $identifier Identificativo utente della richiesta
	 * @return Student
	 */
	public function findByIdentifier($identifier)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('identifier', $identifier));
		$result = $this->findBy($criteria);
		if (is_array($result) && !empty($result)) return $result[0];
		return null;
	}
	
}
