<?php

namespace Application\Entity\Repository;

/**
 * StudentRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepo extends \Doctrine\ORM\EntityRepository
{
}
