<?php

namespace Application\Entity\Repository;

/**
 * StudentgroupRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentgroupRepo extends \Doctrine\ORM\EntityRepository
{
}
