<?php

namespace Application\Entity\Repository;

use Application\Entity\StudentHasCourseHasExam;
use Doctrine\Common\Collections\Criteria;
/**
 * StudentHasAnsweredToItemRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentHasAnsweredToItemRepo extends \Doctrine\ORM\EntityRepository
{
	public function findByStudentCourseExam(StudentHasCourseHasExam $examForStudent)
	{
		$criteria = Criteria::create()->where(Criteria::expr()->eq('studentHasCourseHasExam',$examForStudent));
		$result = $this->matching($criteria);
		if ($result->count()) return $result->getValues();
		return array();
	} 
}
