<?php

namespace Application\Entity\Repository;

/**
 * WeekdayRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekdayRepo extends \Doctrine\ORM\EntityRepository
{
}
